### ISSUE TITLE
Interpreter check cannot be excluded around

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#104]
Example: if you have a shell script that is not styling correctly, you may try to exclude it via

```yaml
restylers:
  - shfmt:
      include:
        - "**/*.sh"
        - "!bin/bad-script"
```

Unfortunately, we check files for shebang only after we've processed includes, so the file is still pull in, despite being explicitly excluded.

See also: https://github.com/restyled-io/restyler/commit/dc1c5d3e32304f7d33062c89d166670473c6118c
