### ISSUE TITLE
Problem with Restyler Job #295241

### ISSUE THREAD

**Issue by csh** [restyled-io/restyler#107]
Hi there-

I'm having a problem with a Restyled Job on a private repository.

- **Restyled Job**: https://restyled.io/gh/csh/repos/mithril-rs/jobs/295241

**What I expected to happen**: 
`rustfmt` to be executed against changed files.

**What happened instead**: 
Job assumes that Rust 2015 edition is being used despite every `Cargo.toml` declaring `edition = "2018"` causing the job to choke at methods declared `async`. Even worse experience when specifying the edition as an argument.

**Configuration** (if applicable):

First attempt:
```yaml
restylers:
- rustfmt
```

Altering the configuration to declare `--edition 2018` as an argument to `rustfmt` yields the following error: 
> Unrecognized option: 'edition 2018'

I have tried a handful of other configurations including manually specifying the `image` and `command` with no success, below is my latest attempt.

```yaml
restylers:
- name: rustfmt
  image: restyled/restyler-rustfmt:v1.4.14-nightly
  command:
  - rustfmt
  - '--edition 2018'
```

I can see that the docker image was built within the last couple of months, meaning it should definitely support 2018 edition Rust however I cannot seem to pinpoint the reason for this behaviour.

**Comment by pbrisbin** [comment]
Hey, sorry for the trouble here! I'm not a Rust developer, so I apologize if this image is resulting in an unexpected or unusual experience.

Adjusting the command-line should work, but I think I spot an issue in your syntax:

```yaml
restylers:
- name: rustfmt
  image: restyled/restyler-rustfmt:v1.4.14-nightly
  command:
  - rustfmt
  - '--edition 2018'
```

This is passing the single, space-containing string `'--edition 2018'` as one argument to `rustfmt`, which makes sense that it'd be rejected as `Unrecognized option: 'edition 2018'`.

To pass the separate command-line arguments `--edition 2018`, as you probably want, Either of the following should work:

```yaml
restylers:
  - rustfmt:
      arguments:
        - "--edition"
        - "2018"
```

```yaml
restylers:
  - rustfmt:
      arguments: ["--edition", "2018"]
```

For some additional context:

- I kept the shorter `- rusfmt:` syntax, but using `name:` would be fine too
- Specifying the `image` shouldn't help or hurt your attempts to change the command-line command
- Adding to `command` works to, but that has a slightly different purpose than `arguments`
- In YAML, you can do Arrays as `-`-lists (first version) or literal Arrays (second version)
- I wrapped all elements in `"` to ensure they're interpreted as Strings, but I'm not sure if that's necessary
- More docs here: https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#restylers-1

It's surprising to me as well that `rustfmt` isn't respecting project-local configuration (e.g. `Cargo.toml`), but there really shouldn't be anything about the Restyler process that affects this behavior, maybe it's a `rustfmt` bug?
