### ISSUE TITLE
Problem with Restyler Job #369013

### ISSUE THREAD

**Issue by Winfidonarleyan** [restyled-io/restyler#118]
Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/WarheadCore/repos/WarheadCore/jobs/369013
- **GitHub PR**: WarheadCore/WarheadCore#38

**What I expected to happen**:
- Successful restyle :D

**What happened instead**:
- Error in `arguments`, I am not entirely sure that I am using the arguments correctly.

**Configuration** (if applicable):

```yaml
enabled: true

exclude:
  - ".github/workflows/**/*"
  - "dep/**"
  - "contrib/**"

changed_paths:
  maximum: 1000
  outcome: error

remote_files: []

auto: false

commit_template: |
  [Restyler] ${restyler.name}
pull_requests: true

comments: false

statuses:
  differences: true
  no_differences: true
  error: true

request_review: none

labels:
  - restyled

ignore_labels:
  - restyled-ignore

restylers_version: stable

restylers:
  - clang-format:
      enabled: false
  - astyle:
      arguments: ["--style=allman --attach-closing-while --indent-switches --indent-namespaces --indent-col1-comments --break-blocks --pad-oper --pad-comma --delete-empty-lines --align-pointer=type --align-reference=type --remove-braces"]
  - "*"
```
