### ISSUE TITLE
Problem with Restyler Job #1605486

### ISSUE THREAD

**Issue by falgon** [restyled-io/restyler#175]
Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/falgon/repos/roki-web/jobs/1605486
- **GitHub PR**: falgon/roki-web#243

**What I expected to happen**:

Restyler starting

**What happened instead**:

The following log is output and restyler does not start

```
restyler: Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_PASSIVE], addrFamily = AF_UNSPEC, addrSocketType = NoSocketType, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "dd-agent", service name: Just "8125"): does not exist (Name or service not known)
```

**Configuration**:

```yaml
enabled: true
restylers:
  - name: stylish-haskell
    include:
      - "**/*.hs"
  - name: dhall-format
    include:
      - "**/*.dhall"
pull_requests: true
statuses:
  differences: true
  error: true
labels:
  - refactoring
ignore_labels:
  - restyled-ignore
```
