### ISSUE TITLE
Problem with Restyler Job #3056822

### ISSUE THREAD

**Issue by yathomasi** [restyled-io/restyler#204]
Hi there-

I'm having a problem with a Restyled Job

- **Restyled Job**: https://restyled.io/gh/iterative/repos/dvc.org/jobs/3056822
- **GitHub PR**: iterative/dvc.org#4459

**What I expected to happen**:
Run without errors

**What happened instead**:
Failed unexpectedly

```yaml
# .restyled.yaml as it was in the commit for the Job
restylers:
  - name: prettier
    arguments: ['--config=./.prettierrc', '--ignore-path=./.prettierignore']
    include:
      - '**/*.css'
      - '**/*.js'
      - '**/*.json'
      - '**/*.jsx'
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.yaml'
      - '**/*.yml'
```
