### ISSUE TITLE
Use as a GitHub Action

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#238]
I've often been asked why Restyled isn't "just" a GitHub Action. The actual reason is that GitHub Actions did not exist at the time I created Restyled. It also _is_ already usable as a GitHub Action: the core restyling functionality is a standalone CLI and corresponding Docker image. Motivated users could install the CLI or pull the image and run it as a GitHub Action. It will restyle the files of the local checkout, after which they could do what they want, be it push those changes or open a sibling PR, just as Restyled does today.

That said, it's harder than it should be and non-obvious how to do so. I would like to see the CLI extended to cater to this use-case, I'd like our own distribution processes more amenable to it (i.e. ship binary-attached Releases instead of, or in addition to, the Docker images), and I'd like a nice `actions/setup` and `actions/run` to exist to encapsulate as much as possible.

I think it would be relatively easy to make the standard "restyle a PR and open a sibling" functionality look like:

```yaml
jobs:
  - uses: actions/checkout@v4
  - uses: restyled-io/actions/setup@v1
  - uses: restyled-io/actions/run@v1
  - uses: peter-evans/create-pull-request@v6
    with:
      branch: ${{ steps.restyler.outputs.restyled-branch-name }}
      base: ${{ github.event.pull_request.head.ref }}
      title: ${{ steps.restyler.outputs.restyled-pr-title }}
      body: ${{ steps.restyler.outputs.restyled-pr-body }}
      delete-branch: true
```

I think leaving the create-pull-request step to the outside is what we should do for now, because it minimizes what we have to change to make this possible and start suggesting it to users, while maximizing flexibility. If/when we decide that GHA is the only way to run Restyled, and we remove all the implementation surrounding the hosted version, we can take a look at what's left before deciding on other trade-offs of ergonomics-vs-complexity.
