### ISSUE TITLE
Embedded languages

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#51]
## Feature

It's common to see something like

```rb
# something.rb
def up
  <<-EOSQL
UPDATE x
  SET y = z
  WHERE q
EOSQL
end
```

It would be great if (assuming we had a SQL restyler) we could use it on the content in between known delimiters in files of other languages (in this case Ruby).

## Implementation Ideas

Add configuration syntax to the `Restyler` element

:warning: **this was not the eventual syntax, see comments below for more up to date examples.**

```yaml
restylers:
  - sql:
      include:
        - "*.sql"

     # new
     embedded:
       - include:
           - "*.rb"
         delimiters:
           - start: "<<-EOSQL"
             end: "^EOSQL"
```

- For any Restylers with `embedded`:
  - For any changed `include` paths:
    - If path contains `delimiters.start/end`:
      - Split the file at the delimiters
      - Place delimited content in new temporary files
      - Restyle those files using that Restyler
      - Splice updated content back into original file

*Assumption*: this is rare enough that we can naively do these gymnastics without feeling a huge performance hit. The upside is we can 100% re-use the embedded-language's existing Restyler as-is and the handling of embedded content is centralized in the restyle process (not any one Restyler).

**Comment by pbrisbin** [comment]
After investigating the mechanics of running Restylers, the following could be a more elegant and broadly-useful implementation:

**Back-pedal recent Configuration change**

Don't move to an object `restylers` key, which forces a Restyler (by name) being run at-most once in a Restyling. The Legacy list-style is all anyone uses now anyway, and that already works like this, so we'll just keep that.

**Add optional `restylers.$name.delimiters`**

Don't mentioned embedded or anything, just have an optional key for delimiting content within an included file that should be Restyled. If delimited, do the tempfile dance described above.

**Handle embedded Restylers _indirectly_**

```yaml
restylers:
  - name: pg_format
    include: "scripts/**/*.sql"

  - name: pg_format
    include: "db/migrate/**/*.rb"
    delimiters:
      start: "<<-EOSQL"
      end: "EOSQL"
```

**Comment by iphydf** [comment]
I like this idea. I'd use it on markdown to format embedded code snippets.

**Comment by pbrisbin** [comment]
I have some WIP for this. Once I build a system for pre-release of Restyler versions, I'd love if you could test it out.

**Comment by iphydf** [comment]
I'll be happy to test pre-releases :). CC me when that's in place.

**Comment by pbrisbin** [comment]
Welp, the configuration changes for #99 just set this back a little bit. The `overrides` approach (again) makes it so any given Restyler is only run once, which means I can't use the "same name different options" to run a Restyler again on delimited content.

In other words, I have to figure out an `overrides` form for:

```yaml
restylers:
  - name: pg_format
    include: "scripts/**/*.sql"

  - name: pg_format
    include: "db/migrate/**/*.rb"
    delimiters:
      start: "<<-EOSQL"
      end: "EOSQL"
```

As `overrides` is written right now, the first override matches so only the first `pg_format` configuration will be run.

**Comment by iphydf** [comment]
That doesn't seem like an inherent problem of the way `overrides` has to be specified, though? I would imagine these scenarios:

**astyle is ran first, then clang-format, then all other restylers**
```yaml
overrides:
  - astyle
  - clang-format
```

**clang-format first, then astyle, then all other restylers**
```yaml
overrides:
  - clang-format
  - astyle
```

**clang-format first, then astyle, then clang-format again, but with different settings, then all other restylers**
```yaml
overrides:
  - clang-format
  - astyle
  - clang-format:
      arguments: ["-style={BasedOnStyle: Google, ColumnLimit: 100}"]
```

**Comment by iphydf** [comment]
This does imply that specifying `overrides` at all changes the order in which restylers are ran. I'd be ok with that as semantics of `overrides`. If you really want all the restylers to run in their original alphabetic order, you can list them explicitly. I can't imagine why you'd want that. I can very much imagine (and I am one of these) wanting to run one C formatter before the other (clang-format, then astyle).

**Comment by pbrisbin** [comment]
So, my current intuition for `overrides` was that it does not modify order. It's basically a lens or mask that is placed over the incoming set of all Restylers, as a `map`-like operation.

I found this necessary once we introduced the wildcard.

```yaml
overrides:
  - astyle
  - "*":
      enabled: false
```

Conceptually, you take all the Restylers and, for each one, apply the first value from the override list that matches it. (This works a bit like `.ssh/config` `Host` declarations, FWIW.) The resulting list is in the order of the original input. Items may have just had overrides applied or not.

When this mapping hits the `astyle` Restyler, the first override matches and so the Restyler is used as-is is. When any other Restyler goes through, `*` is first to match and so it's disabled.

I understand, from a user perspective, how "then all other Restylers" is the experience we want, but I'm not sure how to implement it, especially in the presence of `"*"` as a valid override. And in my experience when it comes to configuration points, complexity of implementation is a smell that there's a problem in the configuration semantics that will actually confuse users, so it's worth paying attention to.

```yaml
overrides:
  - clang-format
  - astyle
  - clang-format:
      arguments: ["-style={BasedOnStyle: Google, ColumnLimit: 100}"]
  - "*":
    enabled: false
```

`clang-format` is a name we can look up in our input list of known Restylers, and "all other restylers" is then any names we haven't looked up yet. That's an implementation that'd satisfy your wildcard-less example.

But `*` is a glob that matches everything in that input list, so it can't work the same way: it can't be recorded as having been looked up, and it can't _lead to_ the definition of "all other Restylers", it's meant to _apply to_ "all other Restylers". And having both possibilities in the same `name` key position breaks my brain...

**Comment by pbrisbin** [comment]
OK, I think I have it.

I'd like to revert the change I just made, go back to the original `restylers` key and make a smaller, backwards-compatible change to it. Specifically, allow a single, final name of `*` which means "any Restylers not yet specified".

```yaml
# run only astyle
restylers:
  - astyle

# run astyle, in a custom way, and all other Restylers after
restylers:
  - astyle:
      arguments: []
  - "*"

# run clang-format, then astyle, then custom clang-format again, an no other Restylers
restylers:
  - clang-format
  - astyle
  - clang-format:
      arguments: ["-style={BasedOnStyle: Google, ColumnLimit: 100}"]
```

This seems to cover all use cases, and has the nice benefit that in-the-wild `restylers` keys of today continue to function exactly as before. Users such as yourself, who want to configure something but retain others as default, just have to ensure they add a finale `"*"` value in the list when they create it. Is that too non-obvious?
