### ISSUE TITLE
Restylers exclude syntax

### ISSUE THREAD

**Issue by pbrisbin** [restyled-io/restyler#55]
It'd be nice to support

```yaml
restylers:
  - "!some-restyler"
```

To accept defaults, minus that one.

**Comment by pbrisbin** [comment]
Also realized it's kind of crappy that if you have to edit `restylers` to, say, enable `brittany`, you've also lost an ability to have default restylers automatically managed now too.

We might want to change the format further?

```yaml
restylers:
  explicit:
  - foo
  - bar

restylers:
  enable:
  - foo

restylers:
  disable:
  - bar

# Keep this as a short-hand for explicit, for backwards-compatibility
restylers:
- foo
- bar
```

An alternative, broader Config format change would be to:

1. Conceptually always have *all* Restylers in `restylers`
1. Because of this, we could have a simple object, not the list-or-single-objects-list
1. Handle defaulting by an `enabled:` key that is off for some in the default set
1. Then

```yaml
# Turning on brittany, but keeping all other defaults
restylers:
  brittany:
    enabled: true

# Excluding prettier, but keeping all other defaults
restylers:
  prettier:
    enabled: false

# Being totally explicit is harder, but is it really ever necessary?
restyler:
  brittany: { enabled: true }
  prettier: { enabled: false }
  # ...
```

Another benefit to this is that the default set of Restylers is determined in their `info.yaml`s; further centralizing this last bit in the restylers repo is a Good Thing IMO.
